# Generated by Django 4.1.3 on 2022-12-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('BestSeller', 'primary'), ('Action', 'success'), ('New', 'danger')], max_length=10, null=True),
        ),
    ]
