# Generated by Django 4.1.3 on 2022-12-07 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_product_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='order',
            name='plastic',
        ),
    ]
