# Generated by Django 4.1.3 on 2022-12-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_remove_order_cash_remove_order_plastic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
