# Generated by Django 4.1.4 on 2022-12-13 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowers.billingaddress'),
        ),
    ]
