# Generated by Django 4.1.4 on 2022-12-13 07:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_order_billingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='countries',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='Uzbekistan', max_length=2),
            preserve_default=False,
        ),
    ]
