# Generated by Django 4.1.4 on 2022-12-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0010_payment_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amont',
            new_name='amount',
        ),
    ]
