# Generated by Django 4.1.7 on 2023-03-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0011_rename_amont_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=20)),
                ('min_price', models.IntegerField()),
                ('discount_cash', models.IntegerField(blank=True, null=True)),
                ('discount_interest', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
