# Generated by Django 4.1.7 on 2023-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0013_order_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
